### PR TITLE
Add more bindings for Haste.Graphics.Canvas

### PR DESCRIPTION
**Pull request by sqd**
`clearRect`
`quadraticCurve`
`bezierCurve`
`renderOnTopBy` (to support different composition stratergies)
`readPixel`
`writePixel`
`modifyPixel`

### CODE REVIEW

**Comment by valderman** [comment]
This is great stuff! There are a few changes I'd like to make though:
* For `renderOnTopBy`, how about swapping the `Picture a` and `CompositionOperation`, to make the function `renderOnTopBy :: MonadIO m => Canvas -> CompositionOperation -> Picture a -> m ()`? Drawing a new frame with the same rendering settings seems to me like it would be a more common operation than redrawing the same scene with different rendering settings, which would make this ordering more convenient. This assumption may be completely incorrect if you're doing multipass rendering though. Do you have a specific use case in mind where putting the `CompositionOperation` at the end is more convenient?
* I'd like to replace any occurrences of `String` by `JSString`, to avoid the conversion from native JS strings to Haskell's list-based string type and back again. I'd also probably like to swap the `lookup` for serializing `CompositionOperation` for an array lookup using `dataToTag` on the operation. Also, I'd refactor the inline `ffi` call in `writePixel` to the top level, since Haste is not always able to fully optimize inline calls to `ffi`.
* I'm a bit concerned about the performance of `writePixel`. Pixel access to a canvas is extremely slow compared to using drawing primitives. This functionality is still very good to have, but maybe the documentation should mention that performance is likely to suffer?

Do these changes make sense?

**Comment by sqd** [comment]
- Your first and second points seem reasonable to me.

- How about providing functions that read/write/modify a batch of pixels in a single call? Without all the converting back and forth, this would be much faster for manipulating many pixels. Plus, people can still manipulate single pixels if they want.

**Comment by valderman** [comment]
How about the following API for pixel manipulation:

    newtype PixelM a deriving (Functor, Applicative, Monad)
    withCanvasPixels :: PixelM a -> Picture a
    withNewPixels :: PixelM a -> Picture a
    setPixel :: Int -> Int -> Color -> PixelM ()
    getPixel :: Int -> Int -> PixelM Color
    setRed/Green/Blue/Alpha :: Int -> Int -> Word8 -> PixelM ()
    getRed/Green/Blue/Alpha :: Int -> Int -> PixelM Word8

This would be relatively straightforward to implement efficiently. The reason for two different pixel drawing functions is that getting the pixel data of an image is relatively slow in most browsers. If you intend to overwrite the entire image, it's faster to just create a new pixel array instead of extracting the image data from the canvas.

**Comment by sqd** [comment]
You mean to modify on the existing canvas by `withCanvasPixels`, and to completely override the existing canvas by `withNewPixels`? If this is the case, the APIs would seem a little weird. The meanings of the combinations of these two functions and `render` and `renderOnTop` may seem unclear.

The rest seems fine for me. Except, well, is it really necessary to provide separate APIs for every channel? It doesn't take much effort to pattern match against Color.

**Comment by valderman** [comment]
Right, it probably makes more sense to provide `renderPixels :: MonadIO m => Canvas -> PixelM () -> m ()` or similar instead for the case where we ignore the previous contents of the canvas.

I'm not too keen on the separate functions for the pixel subchannels either, but pattern matching on `Color` and writing a whole pixel introduces some significant overhead if all you want to do is, for instance, to modify the alpha channel.

**Comment by sqd** [comment]
Sounds good, and how about `renderPixelsOnTop` for modifying the canvas?

The problem is that you simply can't separately read/write a specific channel of a pixel, the js APIs (`getImageData` and `putImageData`) return/accept a whole pixel(and many other things). So the overhead in can't be avoided anyway.

**Comment by valderman** [comment]
While you can't read/write separate channels from/to the canvas, you can still manipulate the raw pixel data on a per channel basis. If you're doing something to each pixel, this is probably where most of your time will be spent anyway, so it would be nice to make this use case as fast as possible.

**Comment by sqd** [comment]
Oh, that's right. Will provide separate functions for each channel.

**Pull request closed without merging**
